import type { GetServerSideProps, NextPage } from "next";

import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import GoogleLoginButton from "../components/auth/GoogleLoginButton";
import styles from "../styles/Home.module.css";
import NavBar from "../components/NavBar";

import { ServersideSessionHandler } from "lib/middleware";
import { Session } from "next-auth";

const Home: NextPage<{ data: Session }> = ({ themeToggler, data: session }) => {
  return (
    <>
      <NavBar themeToggler={themeToggler} session={session} />

      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          {session && <h1>Logged In</h1>}
          {!session && <GoogleLoginButton />}

          <h1 className={styles.title}>Welcome to Chesskid Rating Charts!</h1>

          <p className={styles.description}>
            get your rating data from the chesskid api (see the readme file)
          </p>
          <p>
            then check&nbsp;
            <Link href="/rating">
              <a>Your Rating Charts!</a>
            </Link>
          </p>
        </main>

        <footer className={styles.footer}>
          Powered by <span>♥</span>
        </footer>
      </div>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  return ServersideSessionHandler(context); // dont do this from /home otherwise we get infinite loop
};
