import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Ranking from "components/Ranking";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Your Ranking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>Your ranking goes here:</p>
        <Ranking />
      </main>
    </div>
  );
};

export default Home;
