import fsPromises from "fs/promises";

import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import RankingContainer from "components/RankingContainer";

const Home: NextPage = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Your Ranking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>Your ranking goes here:</p>
        <RankingContainer data={props} />
      </main>
    </div>
  );
};

export async function getStaticProps(context) {
  const jsonData = await fsPromises.readFile(
    "sampleData/shortSample.json",
    "utf8"
  );
  const data = JSON.parse(jsonData);
  return {
    props: data, // will be passed to the page component as props
  };
}

export default Home;
